modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"

[[mods]]
modId="dgmodules"
version="${mod_version}"

displayName="DG Modules"
authors="LikeAzusa2"
description='''
Additional modules for Draconic Evolution
'''

[[dependencies.dgmodules]]
modId="neoforge"
mandatory=true
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.dgmodules]]
modId="draconicevolution"
mandatory=true
versionRange="[3.1.3.625,)"
ordering="AFTER"
side="BOTH"

[[dependencies.dgmodules]]
modId="brandonscore"
mandatory=true
versionRange="[3.2.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.dgmodules]]
modId="curios"
mandatory=true
versionRange="[9.5.1,)"
ordering="AFTER"
side="BOTH"

[[mixins]]
config="mixins/dgmodules.json"
